name: "ESP32 unit tests runner"
description: "Build your ESP32 firmware using IDF SDK, run it at QEMU, parse Unity output and returns JUnit report.xml"
branding:
  color: orange
  icon: check-square
inputs:
  component_name:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.component_name }}
